//==============================================================================================
/*!
	@file  default_wr.h(window resource header)

	@author sein
	@date	
*/
#pragma once
#define	TINY_FONT	"fn16"
#define	SMALL_FONT	"fn22"
#define	NORMAL_FONT	"fn30"
#define	LARGE_FONT	"fn40"
#define	BASEX		104
#define	BASEY		100
#define	BOTTOMY		(100 + 64)
#define DEF_WIDTH	600
#define	NOWLOADING	000_000_00010
#define	FULL_WIDTH	(WINDOW_SIZE_FULL + BASEX)
#define	FULL_HEIGHT	(WINDOW_SIZE_FULL + BASEY)
#define	BASEPATH 		"Assets/KsSoft/Scripts/"
#define	RESOURCE_PATH	"Assets/KsSoft/Resources/windows"
#define	NETWORKPATH			BASEPATH + "Network/"
#define	ITEMPATH			BASEPATH + "Item/"
#define	CHARPATH			BASEPATH + "Char/"
#define	CHATPATH			BASEPATH + "Chat/"
#define	TUTORIALPATH		BASEPATH + "Tutorial/"
#define	SCENEPATH			BASEPATH + "Scene/"
#define	COMMONPATH			SCENEPATH + "Common/"
#define	TITLEPATH			SCENEPATH + "Title/"
#define	NAMEEDITPATH		SCENEPATH + "NameEdit/"
#define	PLAYERCREATEPATH	SCENEPATH + "PlayerCreate/"
#define	TOWNPATH			SCENEPATH + "Town/"
#define	MAINPATH			SCENEPATH + "Main/"
#define	FRIENDPATH			TOWNPATH + "Friend/"
#define	GUILDPATH			TOWNPATH + "Guild/"
#define	HOMEPATH			TOWNPATH + "Home/"
#define	PROFILEPATH			TOWNPATH + "Profile/"
#define	INVENTORYPATH		TOWNPATH + "Inventory/"
#define	GATCHAPATH			TOWNPATH + "Gatcha/"
#define	SHOPPATH			TOWNPATH + "Shop/"
#define	PARTYPATH			TOWNPATH + "Party/"
#define QUESTPATH			TOWNPATH + "Quest/"
#define	QUESTRESULTPATH		MAINPATH + "Result/"
#define	QUESTRESURRECTIONPATH	MAINPATH + "Resurrection/"

/*
	プライオリティ定義
*/
#define	SYSTEM_UI_PRIORITY		256
#define HOME_TAB_PRIORITY		255
#define	PROGRESSBAR_PRIORITY	254
#define	TUTORIAL_PRIORITY		192
#define	MESSAGEBOX_PRIORITY		128
/*
	SE定義
*/
#define	SE_DECIDE		052_000_00030
#define	SE_CANCEL		052_000_00040
#define	SE_CLOSE		052_000_00050
#define	SE_OPEN			052_000_00060
#define	SE_CURSOR		052_000_00110
#define	SE_NOTIFICATION	052_000_00200

/*
	ボタン
*/
#define DEF_BUTTON_LARGE	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=LARGE_FONT

#define DEF_BUTTON_NORMAL	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=NORMAL_FONT

#define DEF_BUTTON_SMALL	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=SMALL_FONT

#define DEF_BUTTON_TINY	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=TINY_FONT

#define DEF_BUTTON_CLOSE	\
	TEX_ID=0,"CLOS?";	\
	SIZE = 80,80

#define DEF_BUTTON_HOME \
    TEX_ID = 100_010_00000,"BTHM?"; \
	SIZE = 80,80  \

#define DEF_BUTTON_BACK \
    TEX_ID = 0,"BTBK?"

#define DEF_BUTTON_RIGHT	\
	CAPTION_COLOR=COLOR32(50,50,50,255);	\
	TEX_ID = 0,"BNSR?";	\
	FONT_KIND=LARGE_FONT;	\
	CAPTION_OFFSET = -20

#define DEF_BUTTON_EMP	\
CAPTION_COLOR=COLOR32(255,140,0,255);	\
	FONT_KIND=NORMAL_FONT

#define DEF_BUTTON_WARN	\
	CAPTION_COLOR=COLOR32(255,0,0,255);	\
	FONT_KIND=LARGE_FONT

#define DEF_BUTTON_MAIL	\
	TEX_ID = 0,"BNCM0"

#define DEF_BUTTON_FAVORITE	\
	TEX_ID = 0,"BNCS0"

#define DEF_BUTTON_PARTY	\
	TEX_ID = 0,"BNCP0"

#define DEF_BUTTON_INVITE	\
	TEX_ID = 0,"INVT0"

#define DEF_BUTTON_TRASH	\
	TEX_ID = 0,"BNCT0"

#define DEF_BUTTON_PRIVATE_CHAT	\
	TEX_ID = 100_000_00001,"BNCC0"

#define DEF_BUTTON_EDIT	\
	TEX_ID = 0,"EDIT0"
#define DEF_BUTTON_RELOAD	\
	TEX_ID = 0,"RLOD0"

#define DEF_BUTTON_BAR_LONG	\
	TEX_ID = 0,"BTNL?";	\
	STYLE = ANCHOR_CENTER|WIN_CTRL_STYLE_TEXT_BOLD;	\
	WHITE_CAPTION_COLOR;	\
	CAPTION_OFFSET = 30;	\
	SIZE = 512,80

#define DEF_BUTTON_REFRESH	\
	TEX_ID = 0,"RLOD?"

#define DEF_BUTTON_FILTER	\
	TEX_ID = 0,"BNFT?"

/*
	ソート
*/
#define DEF_BUTTON_SORT	\
	CAPTION_OFFSET = 0,12;	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=SMALL_FONT	
// ($height = 54)

#define DEF_TEXT_SORT	\
	STYLE = WIN_CTRL_STYLE_TEXT_CENTER|NOHIT;	\
	CAPTION_COLOR=COLOR32(100,100,100,255);	\
	CAPTION = 010_030_00060;	\
	FONT_KIND=SMALL_FONT
// ($x += $w/2; $y -= 2;)

/*
	テキストラベル
*/
#define	DEFAULT_CAPTION_COLOR	CAPTION_COLOR=COLOR32(0,0,0,255)
#define WHITE_CAPTION_COLOR	CAPTION_COLOR=COLOR32(255,255,255,255)
#define DEF_TEXT_MESSAGE_LARGE \
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=LARGE_FONT

#define DEF_TEXT_MESSAGE_MIDIUM \
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=NORMAL_FONT

#define DEF_TEXT_MESSAGE_SMALL \
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=SMALL_FONT

#define DEF_TEXT_MESSAGE_TINY \
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=TINY_FONT

#define DEF_TEXT_NOT_FOUND  \
        WHITE_CAPTION_COLOR;    \
        FONT_KIND=LARGE_FONT

#define DEF_TEXT_ACCOUNT_NAME	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=SMALL_FONT

#define DEF_TEXT_TITLE	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=NORMAL_FONT

#define DEF_TEXT_LEVEL	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=TINY_FONT

#define DEF_TEXT_INFO	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=SMALL_FONT

#define DEF_TEXT_TARGET	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=TINY_FONT

#define DEF_TEXT_INFO_TINY	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=TINY_FONT
	
#define DEF_TEXT_WARN	\
	CAPTION_COLOR=COLOR32(255,0,0,255);	\
	FONT_KIND=SMALL_FONT

#define DEF_TEXT_WARN_NORMAL	\
	CAPTION_COLOR=COLOR32(255,0,0,255);	\
	FONT_KIND=NORMAL_FONT

#define DEF_TEXT_MAIL_MESSAGE	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=TINY_FONT

#define DEF_TEXT_STATUS_TITLE \
	CAPTION_COLOR=COLOR32(255,255,255,255);	\
	FONT_KIND=SMALL_FONT

#define DEF_TEXT_STATUS_LABEL \
	CAPTION_COLOR=COLOR32(130,100,0,255);	\
	FONT_KIND=SMALL_FONT

#define DEF_TEXT_STATUS_VALUE \
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=SMALL_FONT

#define DEF_TEXT_STATUS_TINY_TITLE \
	CAPTION_COLOR=COLOR32(255,255,255,255);	\
	FONT_KIND=TINY_FONT

#define DEF_TEXT_STATUS_TINY_LABEL \
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=TINY_FONT

#define DEF_TEXT_STATUS_TINY_VALUE \
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=TINY_FONT

#define DEF_TEXT_GRAY_TINY \
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=TINY_FONT

#define DEF_TEXT_MONEY \
	CAPTION_COLOR=COLOR32(255,255,255,255);	\
	FONT_KIND=TINY_FONT

#define DEF_TEXT_FRAME_TITLE_WHITE	\
	FONT_KIND=SMALL_FONT;	\
	CAPTION_COLOR=COLOR32(255,255,255,255)

#define DEF_TEXT_FRAME_TITLE_BLACK	\
	FONT_KIND=SMALL_FONT;	\
	WHITE_CAPTION_COLOR

#define DEF_TEXT_UP	\
	FONT_KIND=SMALL_FONT;	\
	CAPTION_COLOR=COLOR32(0,0,255,255)

#define DEF_TEXT_UP_TINY	\
	FONT_KIND=TINY_FONT;	\
	CAPTION_COLOR=COLOR32(0,0,255,255)

#define DEF_TEXT_QUEST_LEVEL	\
	FONT_KIND=NORMAL_FONT;	\
	DEFAULT_CAPTION_COLOR	\

#define DEF_TEXT_PARTY_NAME_TINY	\
	FONT_KIND=TINY_FONT;	\
	WHITE_CAPTION_COLOR

#define DEF_TEXT_PARTY_INFO_TINY	\
	FONT_KIND=TINY_FONT;	\
	WHITE_CAPTION_COLOR

#define DEF_QUEST_SKILL_TEXT	\
	FONT_KIND=SMALL_FONT;	\
	WHITE_CAPTION_COLOR
/*
	ラジオボタン
*/
#define DEF_RADIO_DENT	\
	TEX_ID=0,"BTNT?";	\
	CAPTION_COLOR=COLOR32(30,30,30,220);	\
	FONT_KIND=SMALL_FONT;	\
	SIZE=44*4+16,64;	\
	TEXTURE_OFFSET1 = 0,-10

#define DEF_RADIO_DENT_NARROW	\
	TEX_ID=0,"BTNT?";	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=NORMAL_FONT;	\
	SIZE=144,54;	\
	TEXTURE_OFFSET1 = 0,-10

#define DEF_RADIO_DENT_VERY_NARROW	\
	TEX_ID=0,"BTNT?";	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=SMALL_FONT;	\
	SIZE=140,54;	\
	TEXTURE_OFFSET1 = 0,-10

#define DEF_RADIO_SORT	\
	WHITE_CAPTION_COLOR;	\
	FONT_KIND=SMALL_FONT;	\
	SIZE=44*3+16,64;	\
	STYLE=WIN_CTRL_STYLE_TEXT_LEFT;	\
	CAPTION_OFFSET=16,0

/*
	Chat
*/
#define DEF_TEXT_CHAT \
	CAPTION_COLOR=COLOR32(0,0,0,255);	\
	FONT_KIND=NORMAL_FONT

#define DEF_TEXT_CHAT_NAME \
	CAPTION_COLOR=COLOR32(255,255,255,255);	\
	FONT_KIND=SMALL_FONT

#define DEF_INPUTBOX_CHATPHRASE	\
	CAPTION_COLOR=COLOR32(50,50,50,255);	\
	TEX_ID = 0,"BTNI?";	\
	FONT_KIND=SMALL_FONT

#define DEF_INPUTBOX_CHAT	\
	CAPTION_COLOR=COLOR32(50,50,50,255);	\
	TEX_ID = 0,"TXFI?";	\
	FONT_KIND=TINY_FONT

#define DEF_CHECKBOX_CHAT	\
	CAPTION_COLOR=COLOR32(50,50,50,255);	\
	TEX_ID = 0,"CHEK?";	\
	FONT_KIND=TINY_FONT;	\
	SIZE=150, 44;	\
	CAPTION_OFFSET=28,0

#define DEF_BUTTON_CHAT	\
	CAPTION_COLOR=COLOR32(50,50,50,255);	\
	TEX_ID = 0,"BTNC?";	\
	FONT_KIND=TINY_FONT

/*
	インプットボックス
*/
#define DEF_INPUTBOX	\
	CAPTION_COLOR=COLOR32(50,50,50,255);	\
	TEX_ID = 0,"BTNI?";	\
	FONT_KIND=LARGE_FONT

#define DEF_INPUTBOX_SEARCH	\
	CAPTION_COLOR=COLOR32(50,50,50,255);	\
	TEX_ID = 0,"EDBS?";	\
	FONT_KIND=LARGE_FONT

/*
	テキストボックス
*/
#define DEF_EDITBOX	\
	CAPTION_COLOR=COLOR32(50,50,50,255);	\
	COLOR=COLOR32(220,220,220,255);	\
	FONT_KIND=SMALL_FONT

/*
	フレーム
*/
#define DEF_FRAME	\
	TEX_ID = "FRAME";	\
	COLOR = COLOR32(255,255,255,255-8)

#define DEF_FRAME_LIGHT	\
	TEX_ID ="FRML";	\
	COLOR = COLOR32(225,225,225,255-8)

#define DEF_FRAME_ELEGANCE	\
	TEX_ID ="FRME";	\
	COLOR = COLOR32(255,255,255,255-8)

#define DEF_FRAME_ACTIVE	\
	TEX_ID ="FRML";	\
	COLOR = COLOR32(255,255,0,255-8)

#define DEF_FRAME_PARTY	\
	TEX_ID = "FRAME";	\
	COLOR = COLOR32(255,255,255,255-20)

#define DEF_FRAME_PARTY_INNER	\
	TEX_ID = "FRAME";	\
	COLOR = COLOR32(255,255,255,255-150)

#define DEF_FRAME_RESULT	\
	TEX_ID = "FRAME";	\
	COLOR = COLOR32(255,255,255,255-60)

#define DEF_FRAME_POPUP_DARK	\
	TEX_ID = 0,"FRAME";	\
	COLOR = COLOR32(220,220,220,255)

#define DEF_FRAME_POPUP_BRIGHT	\
	TEX_ID = 0,"FRAME";	\
	COLOR = COLOR32(230,230,230,255)

#define DEF_FRAME_POPUP_VERYBRIGHT	\
	TEX_ID = 0,"FRAME";	\
	COLOR = COLOR32(240,240,240,255)

#define DEF_FRAME_POPUP_TRANSPARENT	\
	TEX_ID = 0,"FRAME";	\
	COLOR = COLOR32(240,240,240,100)

/*
	タブバー
*/
#define DEF_TABBAR	\
	CAPTION_OFFSET = ,34;	\
	FONT_KIND = SMALL_FONT;	\
	SIZE = 96,104;	\
	STYLE = WIN_CTRL_STYLE_TEXT_DENT|WIN_CTRL_STYLE_TEXT_BOLD|ANCHOR_LEFTBOTTOM

#define DEF_TABBAR_TITLE	\
	FONT_KIND = NORMAL_FONT;	\
	STYLE = WIN_CTRL_STYLE_TEXT_DENT|WIN_CTRL_STYLE_TEXT_BOLD|WIN_CTRL_STYLE_TEXT_CENTER|NOHIT

/*
	スクロールバー
*/
#define DEF_SCROLLBAR	\
	COLOR = COLOR32(255,255,255,128)

#define DEF_SCROLLBAR_DARK	\
	COLOR = COLOR32(0,0,0,128)

/*
	経験値メーター
*/
#define DEF_METER	\
	TEX_ID = 0,"HPBK";	\
	COLOR =  COLOR32(64,64,64,64);	\
	TEX_ID1 = 0,"HPBR";	\
	COLOR1 = COLOR32(255,64,0,255);	\
	TEX_ID2 = 0,"HPBR";	\
	COLOR2 = COLOR32(255,153,0,255)

/*
 * チェックボックス
*/
#define DEF_CHECKBOX    \
    TEX_ID = 0,"CHBX?"  \

/*
	Icon
*/
#define DEF_ICON	\
	STYLE = TEXT_CENTER;	\
	TEX_ID  = 100_100_00000,"ICNB0";	\
	TEX_ID1 = 100_100_00000;	\
	TEX_ID2 = 100_100_00000,"BGITL";	\
	TEX_ID3 = 100_100_00000,"ICN1";	\
	TEX_ID4 = 100_100_00000,"STCHP";	\
	TEXTURE_SIZE1 = 90, 90;	\
	TEXTURE_OFFSET2 = 40,4;	\
	TEXTURE_OFFSET3 = 3,2;	\
	TEXTURE_SIZE3 = 114,114;	\
	TEXTURE_SIZE4 = 92,92;	\
	CAPTION = 000_000_00009;	\
	CAPTION_OFFSET = 20,-32;	\
	CAPTION_COLOR = COLOR32(255,198,0,255);	\
	FONT_KIND = TINY_FONT;	\
	SIZE = 90, 90

#define DEF_WEAPON_ICON	\
	STYLE = HIDE;	\
	TEX_ID  = 100_010_00000,"ICNB0";	\
	TEX_ID1 = 100_100_00000;	\
	TEX_ID2 = 100_100_00000,"BGITL";	\
	TEX_ID3 = 100_100_00000,"ICN1";	\
	TEX_ID4 = 100_100_00000,"STCHP";	\
	TEXTURE_SIZE1 = 80,80;	\
	TEXTURE_OFFSET2 = 30,4;	\
	TEXTURE_OFFSET3 = 3,2;	\
	TEXTURE_SIZE3 = 104,104;	\
	TEXTURE_SIZE4 = 82,82;	\
	CAPTION = 000_000_00009;	\
	CAPTION_OFFSET = 38,6;	\
	CAPTION_COLOR = COLOR32(255,198,0,255);	\
	FONT_KIND = TINY_FONT;	\
	SIZE = 80, 80

#define DEF_ICON_EDIT	\
	TEX_ID = 0,"ICNE"

#define DEF_ICON_GUILD	\
	TEX_ID = 0,"ICNG"

#define DEF_ICON_QUEST	\
	TEX_ID = 0,"ICNQ"

#define DEF_ICON_PARTY	\
	TEX_ID = 0,"ICNP"

#define DEF_ICON_FRIEND	\
	TEX_ID = 0,"ICNF"

#define DEF_ICON_TOWN	\
	TEX_ID = 0,"ICNT"

#define DEF_ICON_CONNECT	\
	TEX_ID = 0,"CNCT0"

#define DEF_CHECKBOX_ICON	\
	TEX_ID = "ICBN?";	\
	FONT_KIND = SMALL_FONT;	\
	STYLE = WIN_CTRL_STYLE_ANCHOR_LEFTTOP|WIN_CTRL_STYLE_TEXT_CENTER
